//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducationManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class exams
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public exams()
        {
            this.mark = new HashSet<mark>();
            this.userinexams = new HashSet<userinexams>();
        }
    
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public string Description { get; set; }
        public string Classroom { get; set; }
        public System.TimeSpan Time { get; set; }
        public System.DateTime Create_Date { get; set; }
        public int Course_Id { get; set; }
    
        public virtual course course { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mark> mark { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<userinexams> userinexams { get; set; }
    }
}
