//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducationManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mark
    {
        public int Id { get; set; }
        public int Mark1 { get; set; }
        public int Semester_Id { get; set; }
        public short Status { get; set; }
        public int Academicyear_Id { get; set; }
        public int Class_Id { get; set; }
        public int User_Id { get; set; }
        public int Exams_Id { get; set; }
    
        public virtual academicyear academicyear { get; set; }
        public virtual @class @class { get; set; }
        public virtual exams exams { get; set; }
        public virtual semester semester { get; set; }
        public virtual user user { get; set; }
    }
}
